export const CHANGE_ISLOGGEDIN = 'CHANGE_ISLOGGEDIN';
export const CHANGE_ISADMIN = 'CHANGE_ISADMIN';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_STORAGE_ID = 'SET_STORAGE_ID';
export const SET_CSRFTOKEN = 'SET_CSRFTOKEN';

export default {
  CHANGE_ISLOGGEDIN,
  CHANGE_ISADMIN,
  SET_USER_ID,
  SET_STORAGE_ID,
  SET_CSRFTOKEN,
};